#!/bin/bash
#
# Submit grid engine jobs
set -e
set -o pipefail
GT_NAME="${0##*/}"
name="${GT_NAME}"

# Enable debug mode
if [[ -n "${DEBUG}" ]]; then
  set -x
fi

usage() {
  cat <<EOF
usage: ${GT_NAME} [--version] [--help] [--config <path>] [--dry-run] [--verbose]
          <command> [<args>]

Commands:
   check      Check if gtools are ready to use
   config     Create a user config file
   cmd        Submit a single command
   file       Submit a set of commands listed in a file
   stat       Show the status of submitted jobs
   resub      Resubmit failed jobs
   del        Delete submitted jobs

See \`${GT_NAME} help <command>' for more information on a specific command.
EOF
}

unknown_command() {
  echo "${name}: '$1' is not a ${name} command. See \`${name/-/ } --help'." >&2
}

show_help() {
  case "$1" in
    '')
      usage
      ;;
    gt*)
      man "${MAN_DIR}/gt.1"
      ;;
    *)
      if [[ -e "${MAN_DIR}/gt-$1.1" ]]; then
        man "${MAN_DIR}/gt-$1.1"
        break
      else
        unknown_command "$1"
        exit 1
      fi
      ;;
  esac
}

main() {
  if [[ -z "$1" ]]; then
    usage
    exit 1
  fi

  abspath="$(readlink -f "$0")"
  LOCAL_DIR="${abspath%/*}" # used in the setup script
  . "${LOCAL_DIR}/gt-setup.sh"

  read_config "$@"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --version)
        echo "${GT_NAME}: gtools version ${VERSION}"
        break
        ;;
      --help|help)
        shift
        show_help "$@"
        break
        ;;
      --conf*)
        shift
        CONFIG_FILE="$1"
        read_config "$@" # re-read the config
        ;;
      --dry*)
        DRY_RUN=1
        ;;
      --verbose)
        VERBOSE=1
        ;;
      *)
        if [[ -e "${LOCAL_DIR}/gt-$1.sh" ]]; then
          local cmd="$1"
          shift
          verbose "executing: ${LOCAL_DIR}/gt-${cmd}.sh"
          . "${LOCAL_DIR}/gt-${cmd}.sh" "$@"
          break
        else
          unknown_command "$1"
          exit 1
        fi
        ;;
    esac
    shift
  done
}

main "$@"
